### ISSUE TITLE
 Crates.io publication

### ISSUE THREAD

**Issue by garentyler** [mattbettcher/rustyPixelGameEngine#1]
It would be useful if this repo could be published as a crate so that users can simply add it to the dependencies. Maybe a GitHub action could help?

**Comment by garentyler** [comment]
I made changes to prepare the repo in a pull request in #2.

**Comment by mattbettcher** [comment]
It's far from ready. Once it reaches feature parity with PGE then maybe publish to crates.io? I will accept all pull requests that make sense and help push it along towards that goal. I'm currently deployed to the middle east and don't have much time to work on this project.
